name: udacity_mlops_c4_3
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - mlflow=1.14.1
  - matplotlib=3.3.4
  - pandas=1.2.3
  - numpy=1.21.2
  - pip=20.3.3
  - dvc=3.39.0
  - pip:
    - protobuf==3.19.0
    - aequitas==0.42
    - urllib3==1.26.7